# Generated by Django 5.0.3 on 2024-03-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(max_length=255)),
                ('settlement_city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('opening_hours', models.TextField()),
            ],
        ),
    ]
