# Generated by Django 5.0.3 on 2024-03-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='opening_hours',
            field=models.CharField(choices=[('08:00-18:00', '08:00-18:00'), ('09:00-17:00', '09:00-17:00'), ('10:00-18:00', '10:00-18:00')], max_length=20),
        ),
    ]
